#!/usr/bin/env python
import sys
import unittest
import logging

sys.path.append('..')
import ProjectsDAO

class TestProjectsDAO(unittest.TestCase):
    def setUp(self):
        logging.basicConfig(stream=sys.stderr)
        self.log = logging.getLogger("TestProjectsDAO")

    def create_projects_obj(self):
        return {
            'project1': '/home/test/project1',
            'project2': '/home/test/project2',
            'project3': '/home/test/project3'
        }

    def test_saveJson(self):
        ProjectsDAO.saveProjects(self.create_projects_obj())
